version: "3.3"

services:
  app:
    build: app/
    environment:
      - DJANGO_SETTINGS_MODULE=digital_reputation.settings.dev
    volumes:
      - ./app:/usr/src/app
    command: uwsgi --ini uwsgi.ini
    ports:
    - "8001:8001"

  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
      - ./nginx/conf.d/digital_reputation_dev.conf:/etc/nginx/conf.d/00.conf:ro
      - static:/usr/src/app/static:ro
    depends_on:
      - app

volumes:
  static:
